# Generated by Django 5.0.4 on 2024-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tickets_thumbnail_cart_user_tickets_image'),
    ]

    operations = [
        
    ]
