# Generated by Django 5.0.4 on 2024-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
