# Generated by Django 5.0.4 on 2024-05-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_thumbnail_tickets_image_payment'),
    ]

    operations = [
    
    ]
